# Generated by Django 5.1 on 2024-09-02 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_alter_task_planned_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='<span style="color: red;">This field is specified upon creation and cannot be manually changed later</span>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='tasker.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_effort',
            field=models.IntegerField(default=0, help_text='<span style="color: red;">This field is specified upon creation, then calculated automatically and cannot be manually changed later</span>'),
        ),
    ]
